version: '3.2'

services:
 web:
    build: .
    ports:
      - "8888:8888"
    command: jupyter notebook --allow-root
    # networks:
    #   - vectorial_model_network
#  redis:
#    container_name: redis
#    image: redis:6-alpine
#   #  ports:
#   #    - 6379:6379
#    volumes:
#      - redis_volume:/data
  #  networks:
  #     - vectorial_model_network

# volumes:
#   redis_volume:
#    driver: local
  
# networks:
#   vectorial_model_network: {}