version: '3.1'

services:
 web:
    build: .
    ports:
      - "8889:8889"
    networks:
      - vectorial_model_network
    links:
      - redis
 redis:
   container_name: redis
   image: redis:6-alpine
   ports:
     - 6379:6379
   volumes:
     - redis_volume:/data
   networks:
      - vectorial_model_network

volumes:
  redis_volume:
   driver: local
  
networks:
  vectorial_model_network: {}